;; Schema
;;

CREATE TABLE IF NOT EXISTS Server (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    hostname        VARCHAR(32) NOT NULL,
    nick            VARCHAR(32),
    password        VARCHAR(256),
    enable_tls      BOOLEAN NOT NULL DEFAULT 1 CHECK (enable_tls IN (0,1))
);
CREATE INDEX idx_server ON Server(hostname);

CREATE TABLE IF NOT EXISTS Channel (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    name            VARCHAR(32) NOT NULL,
    related_server  VARCHAR(32) NOT NULL,
    joined          DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_server FOREIGN KEY (related_server) REFERENCES Server(id) ON DELETE CASCADE
);
CREATE TABLE Message(
    id              INTEGER      PRIMARY KEY AUTOINCREMENT,
    related_channel INTEGER      NOT NULL,
    related_server  VARCHAR(32)  NOT NULL,
    created         DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    author          VARCHAR(128) NOT NULL,
    message         TEXT         NOT NULL,
    CONSTRAINT fk_channel FOREIGN KEY (related_channel) REFERENCES Channel(id) ON DELETE CASCADE
    CONSTRAINT fk_server  FOREIGN KEY (related_server) REFERENCES Server(id) ON DELETE CASCADE
);
CREATE INDEX idx_timestamp ON Message(created);

;;CREATE VIRTUAL TABLE Message USING fts3(message);

;; Insert Data
;;
INSERT INTO Server(hostname, enable_tls) VALUES('irc.kerjean.me', 0);
INSERT INTO Channel(name, related_server) VALUES('#nuage', 0);

BEGIN TRANSACTION;
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'dont have theme songs now; just logos and hashtags');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'lampilelo', 'its catchier when you are a kid');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'but if its still catchy and not being a kid');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', '+anymore');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'isBEKaml', 'It was definitely catchy when I was a kid. Now, its purely nostalgia when I listen to that title track');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'Of course, there is just survivorship bias.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'What cartoon theme songs  from the 1960s are even remembered now?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'jetsons, luney tunes, ..');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'batman count ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'Not a cartoon. But apparently the Spider-Man theme song is from the 1960s...');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'the theme intro was toon');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'kodein', 'the flintstones');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'rudybot: remember when the saxophone was an integral part of a band?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'rudybot', 'bpalmer: i play saxophone/to this conversation');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Anonymous', 'Full message body here');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Anonymous', 'Full message body here');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Anonymous', 'Full message body here');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Anonymous', 'Full message body here');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Anonymous', 'Full message body here');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'dont have theme songs now; just logos and hashtags');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'lampilelo', 'its catchier when you are a kid');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'but if its still catchy and not being a kid');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', '+anymore');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'isBEKaml', 'It was definitely catchy when I was a kid. Now, its purely nostalgia when I listen to that title track');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'Of course, there is just survivorship bias.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'What cartoon theme songs  from the 1960s are even remembered now?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'jetsons, luney tunes, ..');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'batman count ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'Not a cartoon. But apparently the Spider-Man theme song is from the 1960s...');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'oni-on-ion', 'the theme intro was toon');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'kodein', 'the flintstones');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bpalmer', 'rudybot: remember when the saxophone was an integral part of a band?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'rudybot', 'bpalmer: i play saxophone/to this conversation');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Fleuv', 'qswz, I read it again but still no ringing alarm bells :(');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'n> /^u/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) true');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'n> /^u.*d$/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) true');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'magic');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'n> /^u.*f.*d$/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) true');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'n> /fine/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) true');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'lol');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'n> /fined/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) true');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'you got fined');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', ':o');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'n> /fined/.test(global.shit)');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) true');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'neo4', 'how does the passport work?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'n>/<?test>fine/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) false');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'D:');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'n>/(<?test>fine)/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) false');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'n>/(?<test>fine)/.test()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) true');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'excerrent');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'n> let re=/(?<shit>fine\w+)/; re.exec().groups;');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) { shit: 'fined' }');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'qswz: that typeof check is completely redundand');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'accessing string.message is fine and will give undefined');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Maxdamantu', 'Unless ECMA262 decides to add a String.prototype.message');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'n> parseInt(/.*/.exec()[0], 36)');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jellobot1', '(okay) 86464843759093');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'the gold number');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'hehe');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'magic number');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'neo4', 'we use steam strategy');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'neo4', 'how to authenticate an ordinary user?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'neo4', 'I am going to make a chat where users will authenticate by using facebook, vk, twitter, steam and they can register their own accounts');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'thykka', 'y tho');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'neo4', 'stennowork: passports methods?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'quick q: gold rot13 algorithm');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'golf*');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'neo4', 'how does passport work?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'let rot13=s=>[...s].map(c=>((c.charCodeAt(0)+13-97)%26)+97).join');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', '+13-97 ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'hmm');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'yea -84');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'just more readable for now');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'readable code golf');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'its wrong tho');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'bbiab');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'it should ignore non-alphas');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'rot13 is srs bsns');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'also uppercase and lowercase chars must be handled separately with that %26+a algo');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'since a is different :p');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'rot13=s=>[...s].map(c=>String.fromCharCode(((c.charCodeAt(0)-84)%26)+97)).join``');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'let s do it simple');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'only smallcase');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'but charCode shit is anti-golf');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'thykka', 'y?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'qswz', 'verbose af');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'so a malicious program could try to allocate the exact memory addresses where it assumes an earlier program has ran (grammar)');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'grr12314', 'but recognising the piece of data as a password is like finding a needle in a needlestack');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'stennowork', 'thats true but at least it reduces entropy');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'h', 'topic is:  Channel website: https://freenode.linux.community | Pastebin: https://paste.linux.community | Need an op? Join ##linux-ops | CoC? ##linux-offtopic, please.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'opi', 'set by sauvin on 19 September 2018, 05:14:08');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'on dists which have packaging which have depends, normally that lib would come in when something is installed needing');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'it');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'murii, what dist do you run');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', '?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'How can I know the permissions of an address (RWX) from within a kernel module?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'By permission of an address, I mean the permission of the page to which the address belongs');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'murii', 'jim - debian and centos');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'murii', 'I have another question: does lsof -i -a -p <pid> list all connected clients to that pid?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'murii', 'if there are any ofc');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Barabacha', 'how can I feed the result of this: whereis ed | cut -f3 -d' ' to cp?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'vlt', 'Barabacha: $()');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Barabacha', 'vlt: nice, thanks');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Ben64', 'why would you do cut on that');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'vlt', 'Barabacha: There should be better tools than 'cut' for path operations.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Triffid', 'u__b3h3m0th: but the kernel can do whatever it likes with any page, no?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Barabacha', 'Ben64 because that is all I know so far');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Ben64', 'what are you trying to accomplish');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Jackneill', 'hey');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Barabacha', 'read the source code of ed');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Jackneill', 'what kind of monospace fonts do you use for terminal?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Barabacha', 'I thought whereis ed would point me to the source code but it was just a manual');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Ben64', 'Barabacha: well that would not do it');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'hays', 'Jackneill: used to be dejavu was a standard choice');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Triffid', 'u__Barabacha: hmm, my konsole is set to 'Hack bold' apparently.. there is several others that are nice.. dejavu sans mono, liberation mono, bitstream mono');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Jackneill', 'hays, i ssee thanks');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'murii, I dunno whats up with the centos, but I do know that debian does have dependency relations between packages... so that if you ask for a package that depends on another, it will get the package you ask for and the package it depends on (if its not already installed) and install them both');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'is there a traceroute implementation that shows the intermediate source addresses in some fashion? (so NAT would show up)');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Triffid', 'u__e: that is what traceroute already does');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'no it doesnt');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__e: you cant get intermediate source from inside, otherwise routers would have no idea how to route the return packet. games and stuff that use UDP tunnelling get the source address via an intermediary match-making server');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'it shows the senders of the ICMP Time Exceeded messages, obviously, but what i want is for it to show the source address of the offending packet as seen by each hop');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'the ICMP message is specced to contain the header of the offending packet');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__e: there is things like http://whatismyip.com/ which will show you your public ip if that is what you are after, but that obviously only works for the final NAT translator, not any intermediaries');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__e: then dial up wireshark and see if it does');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'listen, m not after a networking lesson, i just want to know if a tool exists');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__e: it cant exist if the information isnt actually available');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'yeah but given its in the spec and i dont have access to a machine i can wireshark on right now i thought id just ask');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__e: just tried it here, all the UDP encapsulated in the ICMP TTL exceeded have my LAN ip as the source, not NAT external IPs');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'that is weird, how did they get it?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'is your NAT translating it back');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__e: I guess so');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'that is mildly infuriating');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__e: heh but still demonstrates that the information you are after isnt available this simply ;)');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'yes, but it should be!');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'Hi there! does anyone know how to debug which scripts are read when the gui starts for my distro?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'I have centos 6.5 and I use gnome sometimes and kde sometimes');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'and the gui environment (the PATH for example) is incorrect');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'it is not reading my ~/.bash_profile');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'MrElendig', 'that is because your DE is not spawned trough a bash login shell');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'MrElendig', 'working as intended');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: well of course not. ~/.bash_profile is only read when you create a login *bash* shell, but you are creating kde or gnome sessions which arent bash');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'hmmm');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: perhaps you want ~/.xsession or ~/.xprofile ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'im confused');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'si-Jac', 'deconfuses AndrewPRS ');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'I want to add some stuff to the path');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'I usually do that in .bashrc');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'and use .profile to source .bashrc');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Psi-Jack', 'What?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'the way things originally happened was you logged in with a login shell and then you started your X stuff from said login shell, so everything would inherit environment from a login shell');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'what is the right way to set env vars for gnome for a given user?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: but you are not running bash where you expect these changes to show up, so putting them in bashrc kinda defeats the purpose, no? ~/.xsession is probably the right spot or at least more sensible');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'at the least, .profile not .bashrc');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'looks like ~/.profile is not being read');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Psi-Jack', 'Yes, ~/.xsession');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'MrElendig', 'or pam_env');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Psi-Jack', 'For PATH.. No.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Psi-Jack', 'Not pam_env, too many issues with that.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'is there any comprehensive documentation about this?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'MrElendig', 'for his other vars');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: https://stackoverflow.com/a/48375979 perhaps');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'triffid_Hunter, that article says that .xsession may not be read');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'e', 'hmm, there are RFCs specifying that the error payload is translated. this is tedious');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: use .xprofile then');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: my .xsession is read when I log into kde though');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'how can I tell if it is?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'can I print some echos and see theme somewhere?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: doubt it. you can export some vars and see if they are set inside your session though');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__AndrewPRS: hmm, if you echo ... > /dev/stderr it might show up in ~/.xsession-errors I guess');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'lotharn', 'is there a primer on linux troubleshooting out there somewhere worth anything?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'thanks triffid_Hunter');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'hi does anyone know a good streaming server software ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'for video streaming');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'ty');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'triffid_Hunter, I tried that but looks like its not fine');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Mathisen', 'Reisbowle, OBS ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'AndrewPRS', 'at least, when I run alt+f2 in gnome I do not see programs in my path');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'Mathisen, yeah i know obs , but i would like to have my own server. i thought obs is streaming it to youtube ect.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Mathisen', 'Reisbowle, so just to confirm you want something you can use to stream music,video whatever from your linux server to your other machines ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Mathisen', 'Reisbowle, if this is correct plex or Emby would be a good start');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'Reisbowle, ok i look it up');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'are they free of charge ?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'Reisbowle, i actualy want to stream german tv to a friend in asia');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'Mathisen,');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'XD');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Mathisen', 'yes and no.. some features are behind pay wall but not a must to have');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Reisbowle', 'so it would be great if it supports live streaming');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__b3h3m0th: honestly I do not know that much about kernel internals');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'triffid', 'u__b3h3m0th: I have a general overview of how protected mode functions, but have not dug into this level of detail');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'Anyway, I was trying to alter the PGD of a process. For PoC purpose, I was trying to corrupt to see if I am doing the access right by doing something like this (pseudocode) in my module_init:');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'struct task_struct *task = pid_task(find_vpid(pid_of_the_process), PIDTYPE_PID); struct mm_struct *mm = task->mm!=NULL?task->mm:task->active_mm; cr3_phys = (void *) mm->pgd; cr3_virt = phys_to_virt(cr3_phys); memset(cr3_virt+20, 0, 1000);');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'But I am getting a SIGSEGV on insmod and wondering why!');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'CSan someone explain this duo behaviour??? Here: https://paste.fedoraproject.org/paste/8kq934dphTeORr1pHFpZHw/raw');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'damn its dead tonight.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'hates sudo --command=''');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'sudo is dumb as su - poo');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'strangles a cat');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'a segfault is also where you are trying to access memory that is not actually at the memory address(es) you are trying to access');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'jim, so like an mprotect call could make a segfault in a program if it tries to read privileged memory regions and pages?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'reads a page');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'jim: But this address was what was returned by mm->pgd;');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'and then passed to phys_to_virt');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'autopsy: But how would a program even try to do mprotect call on a privileged memory region? Privileged memory region would not even be mapped into a processs virtual address space right>');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'With an exception to the vsyscall page, for which I guess it should throw a SIGSEGV indeed. never tried.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'epitamizor', 'I am using xfce4 but the mouse icon theme is only working for qt applications and uses default theme for anything else. is there anyway to change it for all applications?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'epitamizor, get a defribulator for it!!');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'huffs and puffs');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'blows his house down');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'wheres the gasoline and matches this sudo is cray-zee!');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'blows his nose');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'blows his pants over sudo');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'vsyscall() thats where it at.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'b3h3m0th, autopsy, maybe the phenominem I am thinking of is called a bus error');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'jim, yes thats a good one.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'jim. got any reasons for this calamity? https://paste.fedoraproject.org/paste/8kq934dphTeORr1pHFpZHw/raw');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'is calamity jane');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'web search revealed this: Segmentation Fault indicates an invalid access to a valid memory, while Bus Error indicates an access to an invalid address.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'Invalid accessing most likely hes facing.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'Not a BUS ERROR.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__hi gais');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'autopsy, Ive never seen that before, what if you try it this way: sudo -u fiche groups');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__is the performance for kvm/qemu drastically better than virtualbox?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__it');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'epitamizor', 'i wouldn t say drastically, but definitely better');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__jim: the difference between vmware workstation and virtualbox is miles apart, but muh FLOSS');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'indent_me, does 'which nc' show a path for nc?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'jim, that works! https://paste.fedoraproject.org/paste/wXX1domz6Fz2FQxN6ZyQdw/raw');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__jim: huh? why bring nc up?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'looking to see the detail of your cpu in a pastebin... if you have nc that makes one of them convenient');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__its just an intel i7-7500U');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'lshw | nc termbin.com 9999');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'indent_me, but the steppings and bogomips and processor flags matter.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'flags a Russian Tanker ship');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'indent_me, oh, then you absolutely have hardware virtualization... make sure it');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'is enabled in your bios');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__it is, it is, just wondering if anyone has experienced crappy performance on vbox as compared to other hypervisors');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__guess Ill give qemu/kvm a shot, with libvirt i guess');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'I couldn t say anything about that specifically, I never tried');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__its painful T_T');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'libvirt is painful?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__oh no vbox');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__unless you are doing headless or a lightweight wm, performance is really bad');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__gnome in particular');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'jim: So basically, whatever address you give in your userland, kernel guarantees its not a privileged page. that is how address virtualization works. I suppose.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'Unless you are in real mode, which can t be in user space.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__1 last thing guys and gals');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__anyone here happen to use/have an apple airpod? whats the compatibiltiy status on nixland?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'jim', 'I am not really familiar with how the kernel does stuff');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'indent', 'e__nvm, thanks guys');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'Nevermind is right!');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'goes away!');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'Kernel doesn t do stuff jim. It does it own thing.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'Fiddles with your children late at night and early at 4AM.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'With the windows open.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'autopsy: :o');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'b3h3m0th', 'What a coincidence. The module I am writing is called fiddle.c!');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'goes down to Georgia with his fiddle made of gold');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'sets up a lemonade stand with a few strands of hair from his old.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'utops', 'goes down to Gerogia');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'b3h3m0th, no it isn t is it really now?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'fiddle.c.brownrecluse');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy', 'fangs(*deep, &fleshwound) -> poison.struct_t');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'autopsy',  'thatll give you a nasty sore on your right vertebre.');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'epitamizor', 'I am using xfce4 but the mouse icon theme is only working for qt applications and uses default theme for anything else. is there anyway to change it for all applications?');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'MrElendig', 'epitamizor: qt and gtk have independent settings, the wiki have some info about unification');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'Analima', 'http://pussy17.6g6.eu');
INSERT INTO Message(related_server, related_channel, author, message) VALUES('irc.kerjean.me', 0, 'bumbar', '_ive tried closing a drive with clonezilla, but it failed and now my new drive is not listed under lsblk or hwinfo --disk, what can i do/try?');
COMMIT;
